ALTER TABLE "payroll"."EmployeeProfile"
ADD COLUMN "taxable" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "payroll"."AttendanceEntry"
ADD COLUMN "workedHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "expectedWorkHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "expectedWorkHoursPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "scheduledWorkDays" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "scheduledWorkDaysPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "absenceDeduction" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "tardinessMinutes" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "aotMinutes" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "aotPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "extraOtPremium" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "regularHolidayHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "regularHolidayPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "specialHolidayHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "specialHolidayPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "totalHolidayPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "coAhop" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "totalAhop" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "withholdingTax" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "sourceGrossIncome" DECIMAL(65,30) NOT NULL DEFAULT 0;

ALTER TABLE "payroll"."PayrollSnapshot"
ADD COLUMN "workedHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "deMinimisPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "otTotalHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "otTotalPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "totalLeaves" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "totalLeavesPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "absenceDeduction" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "tardinessMinutes" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "aotMinutes" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "aotPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "extraOtPremium" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "regularHolidayHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "regularHolidayPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "specialHolidayHours" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "specialHolidayPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "totalHolidayPay" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "coAhop" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "totalAhop" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "withholdingTax" DECIMAL(65,30) NOT NULL DEFAULT 0;
